In [1]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

In [10]:
probs = torch.tensor([0.1,0.9])

# multinomial is a probability distribution
# creates a distribution which reflects the probaibilites
samples = torch.multinomial(probs, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [12]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
print(out)
""" 
    useful for generating text in content, it'll start from zero and 
    use the probability distribution and based on the first character
    to predict the probility of the next character
"""


tensor([1, 2, 3, 4, 5])


In [ ]:
out = torch.trill(torch.ones(5,5)) # triangle lower
out
"""
    Important as when you try to predict the next token in the sequence
    you only know what's in the current history.
    Premise is to ensure we can't predict with the answer, but as we 
    increase in iteration we have more and more history

"""

In [ ]:
# mask_fill -> fills elements where the mask is true

In [15]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False) # train on the weights and is very learnable
print(linear(sample))

tensor([ 9.5356, -2.6911, -2.1538], grad_fn=<SqueezeBackward4>)


In [16]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using the nn.functional.softmax()

softmax_out = F.softmax(tensor1,dim=0)
print(softmax_out)

tensor([0.0900, 0.2447, 0.6652])


In [18]:
# Intialising embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


In [20]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print (a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
